language: csharp
mono: none
dotnet: 2.1.2
script:
- dotnet restore
- dotnet test Mailosaur.Test
env:
  global:
  - secure: "hGxUlbq4vAX5su9h9H7ec+MsO9i2dcZswdT593jNnKr4XtQQSl42lDfWdKcmq6VlVnQvSyw9ObB5MmLq08ePBkanag3S9HBVkJu5iqlUjYpknB9LAW7J1CxIIo3gJ239uSDmqzqADmfRBe+bhV7N5TRJRE/9/FfKouJIQFRCweo="
  - secure: "Ee8oNaj+FtkTEuS+pGJ/S/WJQs0u+zRiig1snyEWzSpWLLQwJk6UZtXm/e166C0nPLDg/NIjvPvtSNtRLQ5iAiQ7rD8R66/OARtdenbJ4008wjx8A4P53j6dO4qtVXElSMdgPRlIjm5rWcrNs8NvESNhHfxyiUf0svu3IXfqF2g="
  matrix:
  - MAILOSAUR_BASE_URL=https://mailosaur.com/ MAILOSAUR_SMTP_HOST=mailosaur.io MAILOSAUR_SMTP_PORT=2525
  - MAILOSAUR_BASE_URL=https://next.mailosaur.com/ MAILOSAUR_SMTP_HOST=ms-smtp.uk MAILOSAUR_SMTP_PORT=2525
notifications:
  slack: mailosaur:CsJ9RruwjqHPKr1Iugk8GDtX
before_deploy:
  - version=`git describe --abbrev=0 --tags` &&
    sed -i s/5\.\[0-9]\.\[0-9]/$version/g Mailosaur/Mailosaur.csproj &&
    sed -i s/5\.\[0-9]\.\[0-9]/$version/g Mailosaur/MailosaurClient.cs
deploy:
  skip_cleanup: true
  provider: script
  script: cd Mailosaur &&
    dotnet pack &&
    dotnet nuget push bin/Debug/Mailosaur.$version.nupkg -s https://www.nuget.org/ -k $DEPLOY_KEY
  on:
    branch: master
    dotnet: 2.1.2
    condition: $MAILOSAUR_BASE_URL = https://mailosaur.com/
    tags: true
